# Single container image to serve pre-built files
FROM nginx:stable-alpine

# Copy our custom nginx config
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Copy pre-built files
COPY ./build /usr/share/nginx/html

# Set permissions
RUN chmod -R 755 /usr/share/nginx/html

# Expose HTTP port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"] 