FROM nginx:stable-alpine

# Copy custom nginx config
COPY docker-nginx.conf /etc/nginx/conf.d/default.conf

# Copy built app
COPY build/ /usr/share/nginx/html/

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"] 