apiVersion: v1
kind: Secret
metadata:
  name: perfectltp-keyvault-secret
  labels:
    app: perfectltp
type: Opaque
data:
  # Key Vault URL (base64 encoded)
  # Replace with your actual Key Vault URL
  AZURE_KEY_VAULT_URL: aHR0cHM6Ly95b3VyLWtleXZhdWx0Lm5hbWUudmF1bHQuYXp1cmUubmV0Lw== 